export const mockEvents = [
  {
    id: "1",
    title: "React Native Workshop",
    date: "2023-01-15",
    location: "Tokyo",
    description: "Learn about React Native development.",
  },
  {
    id: "2",
    title: "JavaScript Conference",
    date: "2023-02-20",
    location: "Osaka",
    description: "Join us to explore advanced JavaScript topics.",
  },
  {
    id: "3",
    title: "Mobile App Design Trends",
    date: "2023-03-05",
    location: "Kyoto",
    description: "Discover the latest trends in mobile app design.",
  },
  // 以下、繰り返しとなるデータ
  {
    id: "4",
    title: "Web Development Best Practices",
    date: "2023-04-10",
    location: "Nagoya",
    description: "Learn the best practices in web development.",
  },
  {
    id: "5",
    title: "UI/UX Design Workshop",
    date: "2023-05-25",
    location: "Hiroshima",
    description: "Explore the principles of good UI/UX design.",
  },
  {
    id: "6",
    title: "Cloud Computing Expo",
    date: "2023-06-30",
    location: "Fukuoka",
    description: "Dive into the world of cloud computing.",
  },
  // 以下、同様の構造で繰り返し
  {
    id: "7",
    title: "React Native Workshop",
    date: "2023-07-15",
    location: "Sapporo",
    description: "Advanced topics in React Native.",
  },
  {
    id: "8",
    title: "JavaScript Conference",
    date: "2023-08-20",
    location: "Sendai",
    description: "Discover new frameworks in JavaScript.",
  },
  {
    id: "9",
    title: "Mobile App Design Trends",
    date: "2023-09-05",
    location: "Kanazawa",
    description: "User experience in mobile app design.",
  },
  // ... 同様にデータを追加
  {
    id: "10",
    title: "Web Development Best Practices",
    date: "2023-10-10",
    location: "Yokohama",
    description: "Responsive web design techniques.",
  },
  {
    id: "11",
    title: "UI/UX Design Workshop",
    date: "2023-11-25",
    location: "Nagasaki",
    description: "Creating user-centric designs.",
  },
  {
    id: "12",
    title: "Cloud Computing Expo",
    date: "2023-12-30",
    location: "Kagoshima",
    description: "Future trends in cloud technology.",
  },
  // ... 以下繰り返し
  {
    id: "13",
    title: "React Native Workshop",
    date: "2024-01-15",
    location: "Tokyo",
    description: "Building cross-platform apps.",
  },
  {
    id: "14",
    title: "JavaScript Conference",
    date: "2024-02-20",
    location: "Osaka",
    description: "JavaScript in 2024: What's new.",
  },
  {
    id: "15",
    title: "Mobile App Design Trends",
    date: "2024-03-05",
    location: "Kyoto",
    description: "Mobile first: The new approach.",
  },
  {
    id: "16",
    title: "Web Development Best Practices",
    date: "2024-04-10",
    location: "Nagoya",
    description: "Modern web development tools.",
  },
  {
    id: "17",
    title: "UI/UX Design Workshop",
    date: "2024-05-25",
    location: "Hiroshima",
    description: "Interactive design for mobile apps.",
  },
  {
    id: "18",
    title: "Cloud Computing Expo",
    date: "2024-06-30",
    location: "Fukuoka",
    description: "Securing your data in the cloud.",
  },
  {
    id: "19",
    title: "React Native Workshop",
    date: "2024-07-15",
    location: "Sapporo",
    description: "Optimizing performance in React Native.",
  },
  {
    id: "20",
    title: "JavaScript Conference",
    date: "2024-08-20",
    location: "Sendai",
    description: "New ECMAScript features in 2024.",
  },
];
